version: "3.3"

services:
  dockergen:
    build:
      context: dockergen
      dockerfile: Dockerfile
    command: -wait 2s -notify '/botadmin/diag.sh /botadmin/build.sh' -watch /botadmin/Dockerfile.tmpl /botadmin/Dockerfile
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./dockergen/config.sh:/botadmin/config.sh:ro

volumes:
  botsome:
